language: go
sudo: false
go:
  - tip
before_install:
  - go get github.com/kardianos/govendor
script:
  - govendor sync
after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
